// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2025-07-15',
  devtools: { enabled: true },

  // Import global CSS
  css: ['./assets/css/main.css'],

  // Enable SSR (default in Nuxt 3, but explicitly stated for clarity)
  ssr: true,

  // Modules
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/seo',
    '@nuxt/image',
    '@pinia/nuxt'
  ],

  // SEO Configuration
  site: {
    url: process.env.SITE_URL || 'https://robertgaunceart.com',
    name: 'Robert Gaunce Art',
    description: 'Watercolor artwork by Robert Gaunce - Nature, wildlife, and portrait commissions. Original artwork and prints available in Paris and Lexington, Kentucky.',
    defaultLocale: 'en',
  },

  // Image configuration
  image: {
    quality: 90,
    formats: ['webp', 'avif'],
  },

  // Global SEO meta tags
  app: {
    head: {
      titleTemplate: '%s | Robert Gaunce Art',
      title: 'Robert Gaunce Art - Watercolor Artist',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { 
          name: 'description', 
          content: 'Original watercolor artwork and commissions by Robert Gaunce. Specializing in nature, wildlife, and portraits. Based in Paris, Kentucky.' 
        },
        { name: 'keywords', content: 'watercolor artist, Kentucky artist, Robert Gaunce, nature art, wildlife art, portrait commissions, Paris KY artist, Lexington KY artist' },
        { name: 'author', content: 'Robert Gaunce' },
        // Open Graph
        { property: 'og:type', content: 'website' },
        { property: 'og:site_name', content: 'Robert Gaunce Art' },
        { property: 'og:locale', content: 'en_US' },
        // Twitter Card
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:creator', content: '@robertgaunceart' },
      ],
      link: [
        { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
        { rel: 'canonical', href: process.env.SITE_URL || 'https://robertgaunceart.com' }
      ],
    },
  },

  // Runtime config for environment variables
  runtimeConfig: {
    public: {
      medusaBackendUrl: process.env.MEDUSA_BACKEND_URL || '',
      medusaApiKey: process.env.MEDUSA_API_KEY || '',
    }
  },

  // Sitemap configuration (will be auto-generated by @nuxtjs/seo)
  sitemap: {
    sources: ['/']
  },

  // Nuxt Image domain configuration
  nitro: {
    prerender: {
      routes: ['/']
    }
  },
})
